//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Period { get; set; }
        public int TempC { get; set; }
        public int FeelsLikeC { get; set; }
        public string WeatherDesc { get; set; }
        public string WeatherIcon { get; set; }
        public int ChanceOfSunshine { get; set; }
    }
}
